# Setting the name, memory of the VM
Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |v|
  v.gui = true
  v.memory = "2048"
  v.name = "Currituck-gnaik2-ConceptCloud"

#Disable USB
  v.customize ["modifyvm", :id, "--usb", "off"]
  v.customize ["modifyvm", :id, "--usbehci", "off"]
end
 
# Provision the VM with JDK, binary and other required files  
 config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get -y -q update
      sudo add-apt-repository -y ppa:webupd8team/java
      sudo apt-get -y -q update
      echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo /usr/bin/debconf-set-selections
      sudo apt-get -y -q install oracle-java8-installer
# Increase Java heap space      
      export _JAVA_OPTIONS="-Xms800m -Xmx1500m"
      sudo apt-get -y install git
      cd /home/vagrant/Desktop
# Clone the git repository      
      sudo git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud.git
      cd /home/vagrant/Desktop/FSE-2014-ConceptCloud
      sudo rm README.md
      sudo cp -r conceptcloud/ /home/vagrant/Desktop/conceptcloud/
      sudo cp -r build-vm/ /home/vagrant/Desktop/build-vm/
      sudo rm -rf /home/vagrant/Desktop/FSE-2014-ConceptCloud 
      cd /home/vagrant/Desktop/build-vm
      sudo rm README.md
      sudo rm Vagrantfile
      cd /home/vagrant/Desktop/build-vm/vm-contents
      
# Disable screen lock and add startup script
     sudo mkdir "/home/vagrant/scripts"
     sudo cp start-tool.sh /home/vagrant/scripts/start-tool.sh
     sudo cp screenlock-disable.sh /home/vagrant/scripts/screenlock-disable.sh
     sudo rm start-tool.sh
     sudo rm screenlock-disable.sh
     sudo chmod -R a+rwx "/home/vagrant/scripts/"     
      
     sudo mkdir "/home/vagrant/.config/autostart"
     sudo cp start-tool.desktop /home/vagrant/.config/autostart/start-tool.desktop
     sudo cp screenlock.lock /home/vagrant/.config/autostart/screenlock.lock
     sudo rm start-tool.desktop
     sudo rm screenlock.lock
     sudo chmod -R a+rwx "/home/vagrant/.config/autostart" 
            
# Copy files such as license, installation to desktop
     sudo cp installation.txt /home/vagrant/Desktop/installation.txt
     sudo cp license.txt /home/vagrant/Desktop/license.txt
     sudo cp README.txt /home/vagrant/Desktop/README.txt
     sudo cp author-demo.desktop /home/vagrant/Desktop/author-demo.desktop
     sudo cp tool-in-vm-demo.desktop /home/vagrant/Desktop/tool-in-vm-demo.desktop
     sudo rm -rf /home/vagrant/Desktop/build-vm
     chown -R vagrant "/home/vagrant/Desktop"
     chmod -R a+rwx "/home/vagrant/Desktop"
         
# Install google chrome
    cd /home/vagrant/Downloads
    apt-get -y -q install libxss1
    apt-get -y -q install libappindicator1
    apt-get -y -q install libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb

# Remove unwanted icons from Launcher
    cd /usr/share/applications && sudo rm -f libreoffice-writer.desktop libreoffice-calc.desktop libreoffice-impress.desktop ubuntu-software-center.desktop ubuntu-amazon-default.desktop firefox.desktop
    sudo apt-get purge firefox firefox-globalmenu firefox-gnome-support 
    update-desktop-database  

# Reboot the VM
     sudo reboot

    SHELL
end
  
