
Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |v|
  v.gui = true
  v.memory = "2048"
  v.name = "Currituck-gnaik2-ConceptCloud"

  #Disable USB
  v.customize ["modifyvm", :id, "--usb", "off"]
  v.customize ["modifyvm", :id, "--usbehci", "off"]
end
   
 config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get -y -q update
     sudo add-apt-repository -y ppa:webupd8team/java
     sudo apt-get -y -q update
     echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo /usr/bin/debconf-set-selections
     sudo apt-get -y -q install oracle-java8-installer
     sudo apt-get -y install git
     cd Desktop
     sudo git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud.git
     sudo chown vagrant:vagrant -R FSE-2014-ConceptCloud
     cd FSE-2014-ConceptCloud
     rm README.md
     cp conceptcloud /home/vagrant/Desktop/conceptcloud
     cp build-vm /home/vagrant/Desktop/build-vm
     rm -rf /home/vagrant/Desktop/FSE-2014-ConceptCloud 
     cd /home/vagrant/Desktop/build-vm
     rm README.md
     rm Vagrantfile
     cd vm-contents
      
     # Disable screen lock
     sudo mkdir "/home/vagrant/scripts"
     sudo cp start-tool.sh /home/vagrant/scripts/start-tool.sh
     sudo cp screenlock-disable.sh /home/vagrant/scripts/screenlock-disable.sh
     rm start-tool.sh
     rm screenlock-disable.sh
     sudo chmod -R a+rwx "/home/vagrant/scripts/"     
      
     sudo mkdir "/home/vagrant/.config/autostart"
     sudo cp start-tool.desktop /home/vagrant/.config/autostart/start-tool.desktop
     sudo cp screenlock.lock /home/vagrant/.config/autostart/screenlock.lock
     rm start-tool.desktop
     rm screenlock.lock
     sudo chmod -R a+rwx "/home/vagrant/.config/autostart" 

     cp installation.txt /home/vagrant/Desktop/installation.txt
     cp license.txt /home/vagrant/Desktop/license.txt
     cp README.txt /home/vagrant/Desktop/README.txt
     cp YoutubeDemo /home/vagrant/Desktop/YoutubeDemo
     rm -rf /home/vagrant/Desktop/build-vm
         
  # Install google chrome
    cd /home/vagrant/Downloads
    apt-get -y -q install libxss1
    apt-get -y -q install libappindicator1
    apt-get -y -q install libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb

   # Remove unwanted icons from Launcher
     cd /usr/share/applications && sudo rm -f libreoffice-writer.desktop libreoffice-calc.desktop libreoffice-impress.desktop ubuntu-software-center.desktop ubuntu-amazon-default.desktop
  
   # Reboot the VM
     sudo reboot

    SHELL
end
  
